# Generated by Django 5.2.4 on 2025-07-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_pedido_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='icones_categorias/'),
        ),
    ]
