# Generated by Django 5.2.4 on 2025-07-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_categoria_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_antigo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_novo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='', upload_to='produtos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
