# Generated by Django 5.2.4 on 2025-07-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='loja_retirada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
