# Generated by Django 5.2.4 on 2025-07-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_pedido_loja_retirada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='opcao_entrega',
            field=models.CharField(blank=True, choices=[('entrega', 'Entrega'), ('retirada', 'Retirada')], max_length=10, null=True),
        ),
    ]
