# Generated by Django 5.2.4 on 2025-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='external_reference',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('pago', 'Pago'), ('pendente', 'Pendente'), ('recusado', 'Recusado')], default='aguardando', max_length=20),
        ),
    ]
