# Generated by Django 5.2.4 on 2025-08-13 12:09

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_pedido_codigo_confirmacao_pedido_confirmado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_confirmacao',
            field=models.CharField(default=store.models.gerar_codigo_unico, max_length=12, unique=True),
        ),
    ]
